before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  ldflags:
    - -s -w -X github.com/ekalinin/pbvm/cmd.pbVersion={{.Version}} -X github.com/ekalinin/pbvm/cmd.pbCommit={{.ShortCommit}} -X github.com/ekalinin/pbvm/cmd.pbBuildDt={{.Date}}
archives:
- replacements:
    386: x86_32
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
